[tool.black]
max-line-length = 100
target_version = ['py36']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git
    | \.virtualenv
    | venv
    | virtualenv
    | virtualenv-osx
    | __pycache__
    | test_content_version
  )/
)
'''
